config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  #
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'profile', to: 'users#profile'
  # Front page shows the options
  root to: 'pages#home'

  # Quiz page
  get '/quiz', to: 'pages#quiz', as: :quiz

  # Spin the wheel page
  get '/wheel', to: 'pages#wheel', as: :wheel

  # Pages for searching/filtering activities and for showing one activity
  resources :activities, only: %i[index show] do
    member do
      post 'toggle_favorite', to: "activities#toggle_favorite"
      post 'toggle_type', to: "activities#toggle_type"
    end
  end




  # User signup with personality attached
  # Check devise docs

  # Share your results
  post '/quiz', to: 'pages#share', as: :share

  # Personalities index
  resources :personalities, only: %i[index]
end

app/models/activity.rb
class Activity < ApplicationRecord
  acts_as_favoritable
  has_many :organisation
  has_many :tags, dependent: :destroy
  has_many :filters, dependent: :destroy
  has_many :types, through: :filters

  validates :name, :description, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :description ],
    associated_against: {
      organisation: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archetype.rb
class Archetype < ApplicationRecord
  belongs_to :personality
  belongs_to :trait
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :type
  belongs_to :activity
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  belongs_to :activity
  validates :name, presence: true
end

app/models/personality.rb
class Personality < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :activity
  belongs_to :trait
end

app/models/trait.rb
class Trait < ApplicationRecord
  has_many :tags, dependent: :destroy
  validates :name, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :filters
  has_many :activities, through: :filters
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_favoritor
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favourites

  validates :email, uniqueness: true

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
before_action :authenticate_user!, only: :toggle_favorite
  def index
    @type = Type.find_by(name: params[:type])
    if @type
      @activities = Activity.joins(:types).where(types: {id: @type.id} )
    else
      @activities = Activity.all
    end
    @activities = @activities.global_search(params[:query]) if params[:query].present?
  end

  def show
    @activity = Activity.find(params[:id])
    @organisation = Organisation.where(activity_id: @activity.id)
  end


  def toggle_favorite
    @activity = Activity.find_by(id: params[:id])
    current_user.favorited?(@activity) ? current_user.unfavorite(@activity) : current_user.favorite(@activity)
  end

  def clicked?
    @activity = Activity.find_by(id: params[:id])
    @favourite = current_user.favorited?(@activity) ? 'fa-heart-clicked' : 'fa-heart'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def quiz

  end

  def wheel

  end

  def results
    # Tag.find_by(trait: Personality.find(1))
    @activities = [Activity.find_by(name: "Community clean up"), Activity.find_by(name: "Teach")]
  end

  def share

  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = current_user
    @personality = Personality.find(@user.personality_id)
  end

  def favourites
    @liked_activities = current_user.all_favorited
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_carousel.html.erb
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <% activity1 = Activity.find(rand(1..10)) %>
    <% activity2 = Activity.find(rand(11..20)) %>
    <% activity3 = Activity.find(rand(21..30)) %>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img  class="d-block w-100" style="filter: brightness(70%)" src="<%= activity1.image%>" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h3><%= activity1.name %></h3>
                <p><%= activity1.description %></p>
            </div>
        </div>
        <div class="carousel-item">
           <img id="clip" class="d-block w-100" style="filter: brightness(70%)" src="<%= activity2.image%>" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h3><%= activity2.name %></h3>
                <p><%= activity2.description %></p>
            </div>
        </div>
        <div class="carousel-item">
            <img id="clip"class="d-block w-100" style="filter: brightness(70%)" src="<%= activity3.image%>" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h3><%= activity3.name %></h3>
                <p><%= activity3.description %></p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="background-color">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 justify-centre">
        <div style="margin-top: 70px" >
          <div class="search-bar">
            <h3>Search</h3>
            <div class="d-flex">
            <div class="search-box">
              <%= form_tag activities_path, method: :get do %>
                <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "Find an activity"
                  %>
            </div>
              <div>
                <%= submit_tag "Search", class: "btn-search" %>
              </div>
              <% end %>
          </div>
       </div>
    </div>
  </div>
</div>

app/views/activities/_like_button.html.erb
<div class="like-icon mx-2
  <%= "fa-heart-clicked" if current_user.favorited?(activity) %>"
  data-id="<%= activity.id %>">
  <i class="far fa-heart heart <%= "fas fa-heart-clicked" if current_user.favorited?(activity) %>"></i>
</div>

app/views/activities/index.html.erb
<div class="background-color">
  <%= render '/shared/navbar' %>
  <div class="activities-container">
    <div class="row">
      <div class="col-lg-12 d-flex justify-content-center">

          <div class="search-bar">
            <h1 class="search-title">Explore a range of activities</h1>
            <div class="d-flex">
            <div class="search-box">
              <%= form_tag activities_path, method: :get do %>
                <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "What would you like to do?"
                  %>
            </div>
              <div>
                <%= submit_tag "Search", class: "btn-search" %>
              </div>
              <% end %>
          </div>
    </div>
  </div>
  </div>
</div>


      <%# Search by activity types %>
<div class="row">
<div class="col-12 justify-center">
    <div class="icon">
      <div id="activity-filters-anchor" style="transform: translateY(-150px);"></div>
      <% Type.all.each do |type| %>
        <% if params[:type] == type.name %>
          <%= link_to  activities_path(anchor: 'activity-filters-anchor'), class: "activity-filter #{'active' if params[:type] == type.name}" do  %>
            <img src="<%= type.image %>" alt="" class="type-image">
            <%= type.name %>
          <% end %>
        <% else %>
          <%= link_to  activities_path(type: type.name, anchor: 'activity-filters-anchor'), class: "activity-filter #{'active' if params[:type] == type.name}" do  %>
            <img src="<%= type.image %>" alt="" class="type-image">
            <%= type.name %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%# Cards %>
<div class="background-color">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 justify-centre">

        <div class="main-container">
          <div class="cards">
            <% @activities.each do |activity| %>

              <div class="card">
                <img class="card-img-top" src="<%= activity.image %>" alt="picture">
                <div class="card-body">
                <h3 class="card-title"><%= activity.name %></h3>
                <p class="card-text"><%= activity.description.truncate_words(20) %></p>
                  <div class="card-link">
                   <% if user_signed_in? %>
                    <%= link_to toggle_favorite_activity_path(activity), remote: true, method: :post do %>
                    <%= render 'activities/like_button', activity: activity %>
                    <% end %>
                    <% end %>
                    <div>
                      <a href="<%= activity_path(activity) %>" class="btn-card">See activity</a>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class="activity-show-background" style="height: 100%">
  <%= render '/shared/navbar' %>
  <div class="container activity-main">
    <div class="activity-name">
      <h1><span class="activity-name-title"><%= @activity.name %></span></h1>
    </div>
    <img src="<%= @activity.image %>" alt="" class="activity-image" />
    <p class="activity-description"><%= @activity.description %></p>
  </div>

  <div class="container activity-connect">
    <h2><span>Check out these organisations</span></h2>
    <div class="container border-connect">
      <ul>
        <% @activity.organisation.each do |organisation| %>
          <p><li><img src="https://cdn-icons-png.flaticon.com/512/1828/1828614.png" width="2%"><a href=<%= organisation.url %> class="org-link"> <%= organisation.name %></a></li></p>
        <% end %>
      </ul>
    </div>
  </div>
  <br><br>
</div>